# Generated by Django 5.0 on 2024-10-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_rename_userprofile_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_secret",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
