# Generated by Django 5.0 on 2024-11-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_user_mfa_enabled_user_mfa_secret"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["first_name", "last_name", "email"],
                name="account_use_first_n_210602_idx",
            ),
        ),
    ]
