# Generated by Django 5.0 on 2024-12-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_user_account_use_first_n_210602_idx"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProxyUser",
        ),
    ]
