# Generated by Django 5.0 on 2024-12-06 14:51

import account.managers
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_delete_proxyuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyUser",
            fields=[],
            options={
                "verbose_name": "Proxy User",
                "verbose_name_plural": "Proxy Users",
                "ordering": ("-pk",),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("account.user",),
            managers=[
                ("people", django.db.models.manager.Manager()),
                ("objects", account.managers.CustomerManager()),
            ],
        ),
    ]
