# Generated by Django 5.0 on 2024-12-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_proxyuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mfa_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
