# Generated by Django 5.0 on 2024-12-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_alter_user_mfa_secret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="photo",
        ),
    ]
