# Generated by Django 5.0 on 2024-12-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_remove_profile_email_remove_profile_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="phone_number",
        ),
    ]
