# Generated by Django 5.0 on 2026-02-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0019_remove_user_avatar_remove_user_birth_date_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="account_use_first_n_210602_idx",
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["first_name"], name="account_use_first_n_ec5d9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["last_name"], name="account_use_last_na_0444d4_idx"
            ),
        ),
    ]
