# Generated by Django 5.0 on 2024-11-14 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_alter_subscription_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="subscription",
            name="subscriptio_subscri_07270d_idx",
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=[
                    "subscriber_name",
                    "subscription_plan",
                    "paypal_subscription_id",
                ],
                name="subscriptio_subscri_77f949_idx",
            ),
        ),
    ]
