# Generated by Django 5.0 on 2024-12-11 20:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0009_remove_subscription_subscriptio_subscri_07270d_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1024, null=True),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("paypal_plan_id", models.CharField(max_length=300, unique=True)),
                ("has_thumbnail_200px", models.BooleanField(default=True)),
                ("has_thumbnail_400px", models.BooleanField(default=False)),
                ("has_original_photo", models.BooleanField(default=False)),
                ("has_binary_link", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["cost"],
            },
        ),
        migrations.RemoveField(
            model_name="premium",
            name="basic_ptr",
        ),
        migrations.RemoveField(
            model_name="enterprise",
            name="premium_ptr",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="user",
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paypal_subscription_id",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("create_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Subscription",
                "verbose_name_plural": "User Subscriptions",
            },
        ),
        migrations.DeleteModel(
            name="Basic",
        ),
        migrations.DeleteModel(
            name="Enterprise",
        ),
        migrations.DeleteModel(
            name="Premium",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
        migrations.AddIndex(
            model_name="usersubscription",
            index=models.Index(
                fields=["paypal_subscription_id"], name="subscriptio_paypal__67b292_idx"
            ),
        ),
    ]
