# Generated by Django 5.0 on 2024-12-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0010_subscriptionplan_remove_premium_basic_ptr_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(fields=["cost"], name="subscriptio_cost_5b65ea_idx"),
        ),
        migrations.AddIndex(
            model_name="subscriptionplan",
            index=models.Index(fields=["name"], name="subscriptio_name_3379a2_idx"),
        ),
    ]
