# Generated by Django 5.0 on 2025-07-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0011_subscriptionplan_subscriptio_cost_5b65ea_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
