# Generated by Django 5.0 on 2024-11-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_remove_images_subscription_images_subscription_plans"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={
                "ordering": ["-created_at", "updated_at"],
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
        migrations.AddIndex(
            model_name="images",
            index=models.Index(
                fields=["title", "author"], name="images_imag_title_162072_idx"
            ),
        ),
    ]
