# Generated by Django 5.0 on 2024-12-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_alter_images_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="description",
            field=models.TextField(max_length=1024),
        ),
    ]
