# Generated by Django 5.0 on 2024-12-11 15:10

import django.core.validators
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0005_alter_images_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="images",
            name="quantity",
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name="images",
            name="total_quantity",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("quantity"), "*", models.F("price")
                ),
                output_field=models.DecimalField(decimal_places=2, max_digits=10),
            ),
        ),
    ]
