# Generated by Django 5.0 on 2024-12-11 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0006_images_price_images_quantity_images_total_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="images",
            name="title",
            field=models.CharField(max_length=200, validators=[django.core.validators.MinValueValidator(3)]),
        ),
    ]
