# Generated by Django 5.0 on 2024-12-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0007_alter_images_price_alter_images_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
