# Generated by Django 5.0 on 2025-07-10 20:51

import django.core.validators
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0008_alter_images_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="author",
            field=models.CharField(
                help_text="Author of the image", max_length=200, verbose_name="author"
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the image was created",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the image",
                max_length=1024,
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(
                help_text="Image file to be uploaded",
                upload_to="images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg", "gif"]
                    )
                ],
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price of the image in USD",
                max_digits=10,
                verbose_name="price",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Quantity of the image available",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="quantity",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="subscription_plans",
            field=models.CharField(
                choices=[
                    ("Basic", "Basic Plan"),
                    ("Premium", "Premium Plan"),
                    ("Enterprise", "Enterprise Plan"),
                ],
                default="Basic",
                help_text="Subscription plan required to access this image",
                max_length=200,
                verbose_name="subscription plans",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="title",
            field=models.CharField(
                help_text="Title of the image",
                max_length=200,
                unique=True,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="total_quantity",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("quantity"), "*", models.F("price")
                ),
                help_text="Total value of the image based on quantity and price",
                output_field=models.DecimalField(decimal_places=2, max_digits=10),
                verbose_name="total quantity",
            ),
        ),
        migrations.AlterField(
            model_name="images",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the image was last updated",
                verbose_name="updated at",
            ),
        ),
    ]
