# Generated by Django 5.0 on 2026-04-03 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0009_alter_images_author_alter_images_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price of the image in USD",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="price",
            ),
        ),
    ]
