# Generated by Django 5.0 on 2024-12-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contactus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Books",
        ),
    ]
