# Generated by Django 5.0 on 2025-07-10 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_delete_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the message was created",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="Email address for contact",
                max_length=255,
                validators=[
                    django.core.validators.EmailValidator(
                        message="Invalid email address"
                    )
                ],
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="message",
            field=models.TextField(
                help_text="Message content", max_length=1024, verbose_name="message"
            ),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Full name of the person contacting us",
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        message="Name must contain only alphabetic characters and spaces",
                        regex="^[a-zA-Z ]*$",
                    ),
                ],
                verbose_name="name",
            ),
        ),
    ]
